[package]
name = "rust_compiler"
version = "0.1.0"
authors = ["佐藤 開智 <revofal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.5.2"
anyhow = "1.0.34"
clap = "3.0.0-beta.2"
